### ISSUE TITLE
bf luis:test crashes

### ISSUE THREAD

**Issue by scheyal** [microsoft/botframework-cli#1072]
## Versions
What CLI version are you using.
@microsoft/botframework-cli/4.10.0-dev.20200730.3786d10 win32-x64 node-v12.18.4

What Nodejs version are you using
v12.18.4

What command-line interpreters are you using
Windows cmd.exe

What OS are you using
Windows

## Describe the bug
See repro. Trying to run bf luis:test and it fails. It used to work recently, before this upgrade.

## To Reproduce
```
>bf luis:test --subscriptionKey %LUISKEY% --endpoint %LUISHOST% --appId %LUISAPP% --in %TESTFILE% --out report\luisresult.txt
Error: Cannot find module 'antlr4/index'
Require stack:
- C:/Users/eyals/AppData/Roaming/npm/node_modules/@microsoft/botframework-cli/node_modules/@microsoft/bf-lu/lib/parser/lufile/generated/LUFileLexer.js
- C:/Users/eyals/AppData/Roaming/npm/node_modules/@microsoft/botframework-cli/node_modules/@microsoft/bf-lu/lib/parser/lufile/luParser.js
- C:/Users/eyals/AppData/Roaming/npm/node_modules/@microsoft/botframework-cli/node_modules/@microsoft/bf-lu/lib/utils/filehelper.js
- C:/Users/eyals/AppData/Roaming/npm/node_modules/@microsoft/botframework-cli/node_modules/@microsoft/bf-luis-cli/lib/commands/luis/test.js
- C:/Users/eyals/AppData/Roaming/npm/node_modules/@microsoft/botframework-cli/node_modules/@oclif/config/lib/plugin.js
- C:/Users/eyals/AppData/Roaming/npm/node_modules/@microsoft/botframework-cli/node_modules/@oclif/config/lib/config.js
- C:/Users/eyals/AppData/Roaming/npm/node_modules/@microsoft/botframework-cli/node_modules/@oclif/config/lib/index.js
- C:/Users/eyals/AppData/Roaming/npm/node_modules/@microsoft/botframework-cli/node_modules/@oclif/command/lib/command.js
- C:/Users/eyals/AppData/Roaming/npm/node_modules/@microsoft/botframework-cli/node_modules/@oclif/command/lib/index.js
- C:/Users/eyals/AppData/Roaming/npm/node_modules/@microsoft/botframework-cli/bin/run
    at Module.patchedRequire [as require] (C:/Users/eyals/AppData/Roaming/npm/node_modules/@microsoft/botframework-cli/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
    at Object.<anonymous> (C:/Users/eyals/AppData/Roaming/npm/node_modules/@microsoft/botframework-cli/node_modules/@microsoft/bf-lu/lib/parser/lufile/generated/LUFileLexer.js:4:14)
```

## Expected behavior
Works as it used to.

## Additional context
This used to work before latest update on my machine.

**Comment by munozemilio** [comment]
This is fix in the latest release and daily builds
