### ISSUE TITLE
qnamaker:init cannot find module antlr4/index

### ISSUE THREAD

**Issue by piquet-h** [microsoft/botframework-cli#1086]
## Versions
What CLI version are you using.
@microsoft/botframework-cli/4.11.1 darwin-x64 node-v15.5.0
What Nodejs version are you using
v15.5.0
What command-line interpreters are you using
zsh
What OS are you using
OSX

## Describe the bug
piquet@Peters-iMac implementation % bf qnamaker:init
Error: Cannot find module 'antlr4/index'
Require stack:
- /Users/piquet/.local/share/@microsoft/botframework-cli/node_modules/@microsoft/bf-lu/lib/parser/lufile/generated/LUFileLexer.js
- /Users/piquet/.local/share/@microsoft/botframework-cli/node_modules/@microsoft/bf-lu/lib/parser/lufile/luParser.js
- /Users/piquet/.local/share/@microsoft/botframework-cli/node_modules/@microsoft/bf-lu/lib/utils/filehelper.js
- /Users/piquet/.local/share/@microsoft/botframework-cli/node_modules/@microsoft/bf-qnamaker/lib/utils/qnamakerbase.js
- /Users/piquet/.local/share/@microsoft/botframework-cli/node_modules/@microsoft/bf-qnamaker/lib/commands/qnamaker/init.js
- /usr/local/lib/node_modules/@microsoft/botframework-cli/node_modules/@oclif/config/lib/plugin.js
- /usr/local/lib/node_modules/@microsoft/botframework-cli/node_modules/@oclif/config/lib/config.js
- /usr/local/lib/node_modules/@microsoft/botframework-cli/node_modules/@oclif/config/lib/index.js
- /usr/local/lib/node_modules/@microsoft/botframework-cli/node_modules/@oclif/command/lib/command.js
- /usr/local/lib/node_modules/@microsoft/botframework-cli/node_modules/@oclif/command/lib/index.js
- /usr/local/lib/node_modules/@microsoft/botframework-cli/bin/run
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:925:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at Module.patchedRequire [as require] (~/.local/share/@microsoft/botframework-cli/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (~/.local/share/@microsoft/botframework-cli/node_modules/@microsoft/bf-lu/lib/parser/lufile/generated/LUFileLexer.js:4:14)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)

## To Reproduce
1. npm install -g @microsoft/botframework-cli
2. bf qnamaker:init
3.
## Expected behavior
It should create an init file.

[bug]

**Comment by munozemilio** [comment]
Hi @piquet-h, we dont support node versions higher than 13 at the moment. Sorry for the inconvenience.
