### ISSUE TITLE
Orchestrator fails with multilingual model on Azure Sites

### ISSUE THREAD

**Issue by nephinj** [microsoft/botframework-cli#1287]
## Versions
@microsoft/botframework-cli/4.14.1 
win32-x64 
node-v14.13.0

## Describe the bug
When building a model with pretrained.20210205.microsoft.dte.00.06.unicoder_multilingual.onnx azure sites does not seem to find the model or thinks it is corrupt.  Code works in the emulator and with ngork when running it locally.  If I switch to the default English model it all works fine locally and on Azure Sites.

## To Reproduce
1.  Add data sources to the model from QnAMaker. 
`bf orchestrator:add -t qna --id "<your id here>" -k "<key here>" --routingName <routing name>`
2. Create the model
```
md model
bf orchestrator:basemodel:get --versionId=pretrained.20210205.microsoft.dte.00.06.unicoder_multilingual.onnx --out ./model
```
3. Create the generated 
```
md generated
cd CognativeModels
bf orchestrator:create --hierarchical --in CognitiveModels --model ../model --out ../generated

```
## Expected behavior
Expect code to find the model and return the right result if using the English or multi-lingual model.

## Screenshots
Error in the log file:
Hosting environment: Production
Content root path: D:\home\site\wwwroot
Now listening on: http://127.0.0.1:45432
Application started. Press Ctrl+C to shut down.
EXCEPTION THROWN - utility_onnx::OnnxUtility::InitOnnxSession(): e.what()=Load model from D:\home\site\wwwroot\model\model.onnx failed:bad allocation, __FILE__=D:\a\1\s\oc\utility\OnnxUtility.h, __LINE__=117
EXCEPTION THROWN - OC - EmbedderBase::EmbedderBase(json const& config, const string onnxVocabFileDefault, const string onnxModelFileDefault): e.what()=Load model from D:\home\site\wwwroot\model\model.onnx failed:bad allocation, FILE=D:\a\1\s\oc\EmbedderBase.cc, LINE=57
fail: Microsoft.Bot.Builder.Integration.AspNet.Core.BotFrameworkHttpAdapter[0]
      [OnTurnError] unhandled error : Failed to find or load Model with path D:\home\site\wwwroot\model
System.InvalidOperationException: Failed to find or load Model with path D:\home\site\wwwroot\model
 ---> System.ApplicationException: Load model from D:\home\site\wwwroot\model\model.onnx failed:bad allocation
   at Microsoft.BotFramework.Orchestrator.Orchestrator..ctor(String baseModelConfigOrPath)
   at Microsoft.Bot.Builder.AI.Orchestrator.OrchestratorRecognizer.<InitializeModel>b__39_0(String path)
   --- End of inner exception stack trace ---
   at Microsoft.Bot.Builder.AI.Orchestrator.OrchestratorRecognizer.<InitializeModel>b__39_0(String path)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Bot.Builder.AI.Orchestrator.OrchestratorRecognizer.InitializeModel()
   at Microsoft.Bot.Builder.AI.Orchestrator.OrchestratorRecognizer.RecognizeAsync(DialogContext dc, Activity activity, CancellationToken cancellationToken, Dictionary`2 telemetryProperties, Dictionary`2 telemetryMetrics)
   at SSC.Chatbot.QnABot`1.OnMessageActivityAsync(ITurnContext`1 turnContext, CancellationToken cancellationToken) in D:\a\1\s\Bots\QnABot.cs:line 121
   at Microsoft.Bot.Builder.ActivityHandler.OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken)
   at SSC.Chatbot.QnABot`1.OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken) in D:\a\1\s\Bots\QnABot.cs:line 97
   at Microsoft.Bot.Builder.TelemetryLoggerMiddleware.OnTurnAsync(ITurnContext context, NextDelegate nextTurn, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Integration.ApplicationInsights.Core.TelemetryInitializerMiddleware.OnTurnAsync(ITurnContext context, NextDelegate nextTurn, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.BotFrameworkAdapter.TenantIdWorkaroundForTeamsMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.MiddlewareSet.ReceiveActivityWithStatusAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.BotAdapter.RunPipelineAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken)

Bot displayed error:
![Bot error](https://user-images.githubusercontent.com/2805536/130834643-3ed0f8d7-b8b6-4120-a070-057200747a68.png)

File seems to exist at the location it is looking:
![Azure Console](https://user-images.githubusercontent.com/2805536/130834769-b1f5eeb1-3612-4d81-997a-591d31a5891d.png)

## Additional details
Tested with the following models:
(fails)  --versionId=pretrained.20210205.microsoft.dte.00.06.unicoder_multilingual.onnx 
(fails) --versionId=pretrained.20201210.microsoft.dte.00.12.unicoder_multilingual.onnx 
(works) --versionId=pretrained.20210608.microsoft.dte.01.06.int.unicoder_multilingual.onnx
(works) no versionId specified.

[bug][Orchestrator]

**Comment by nephinj** [comment]
Switching to x64 and bumping the memory to 14GB did not  help.  I can see 6GB of memory free in application insights.  
![image](https://user-images.githubusercontent.com/2805536/131349935-78a0db71-0f71-4a23-a872-fbe9cfa8ab38.png)

**Comment by hcyang** [comment]
Hi @nephinj, please give us the exact Azure VM config you are using, so we can repro. Thanks.

**Comment by nephinj** [comment]
It is running on Azure App Service with these settings:
![image](https://user-images.githubusercontent.com/2805536/131384626-1caded16-2517-4212-9ca0-64c1eb4028bf.png)
![image](https://user-images.githubusercontent.com/2805536/131384670-8dcdaa8e-1831-4e9a-86b7-b5f1bf101748.png)

**Comment by hcyang** [comment]
Hi @nephinj, thanks for the Azure configuration. We can repro the issue on an Azure VM. Will debug,

**Comment by hcyang** [comment]
Hi @nephinj, we suspect that you might be using a x86 nodejs installation in your Azure VM, thus the bf-cli packages were also installed as their 32-bit versions. Please double check if your Azure VM were installed with x64 version or not.

**Comment by hcyang** [comment]
Hi @nephinj, I think this issue is well understood and can be closed. Let us know if you have more questions.

**Comment by hcyang** [comment]
Hi @nephinj, I think this issue is well understood and can be closed. Let us know if you have more questions.

**Comment by munozemilio** [comment]
Hi @nephinj I'm closing this due to inactivity. Feel free to reopen if needed
