### ISSUE TITLE
Error: Cannot find module @microsoft/orchestrator-core/orchestrator-core.node

### ISSUE THREAD

**Issue by ChiragM-Hexaware** [microsoft/botframework-cli#1346]
## Versions
What CLI version are you using = 4.15.0
What Nodejs version are you using = 14.2.0
What command-line interpreters are you using=  Putty
What OS are you using = Linux Redhat(8.2)

## Describe the bug
After installing @microsoft/botframework-cli with npm. It got installed successfully. But when i tried creating a snapshot file with bf orchestrator:create command. It is showing Error: Cannot find module '/usr/local/lib/node_modules/@microsoft/botframework-cli/node_modules/@microsoft/orchestrator-core/orchestrator-core.node'. Please verify that the package.json has a valid "main" entry
    at Module.patchedRequire [as require] (/usr/local/lib/node_modules/@microsoft/botframework-cli/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
    at Object.<anonymous> (/usr/local/lib/node_modules/@microsoft/botframework-cli/node_modules/@microsoft/bf-orchestrator/lib/labelresolver.js:14:12)
Package json main entry is correct. But when i opened node_modules folder -> @microsoft, -> orchestrator-core. There is no .node file present after installation. But after installation of bf cli(which i did before), Output came up as * @microsoft/orchestrator-core] **Success:** "/usr/local/lib/node_modules/@microsoft/botframework-cli/node_modules/@microsoft/**orchestrator-core/orchestrator-core.node" is installed via remote**. So don't know why i can't find .node file

## To Reproduce
1. Install npm -g @microsoft/botframework-cli
2. Give any bf cli command for orchestrator
3. I gave bf orchestrator:create
4. See error as mentioned above

## Expected behavior
It should create a orchestrator snapshot file in specified folder. None of orchestrator command is working

**Comment by gabog** [comment]
Hi @munozemilio, can you please take a look at this issue?
Thanks

**Comment by munozemilio** [comment]
Hello @ChiragM-Hexaware. Thanks for taking the time to report this issue. Do you get error messages for other command groups? e.g bf config:show .... bf: luis:convert ? I have seen issues similar to this when the CLI got installed with different permissions and then ran with others. In the meantime, I will try to replicate your environment since I don't have one handy.

**Comment by phasselhoff** [comment]
The issue may be linked to the lack of a package lock file in the project @microsoft/orchestrator-core/orchestrator-core.node. the lack of this package lock file may be causing the orchestrator files to not be installed because non compliant dependencies may be brought in because there is no lock.

**Comment by munozemilio** [comment]
thank you all for the feedback:
I ran the command in UNIX a works just fine:
![Screen Shot 2022-06-14 at 11 14 19 PM](https://user-images.githubusercontent.com/43281931/173771299-eb6795e9-6f10-4c46-a39a-97f3f84b7aab.png)

I will do a re image and try in a clean state.

**Comment by phasselhoff** [comment]
The missing package lock would probably result in an error that possibly only occurs intermittently.

**Comment by axelsrz** [comment]
Closing this issue as this was a specific customer environment problem. This was fixed privately offline.
