### ISSUE TITLE
[Orchestrator] Fail to install microsoft/bf-orchestrator-cli@beta

### ISSUE THREAD

**Issue by DingmaomaoBJTU** [microsoft/botframework-cli#973]
## Versions
What CLI version are you using.
What Nodejs version are you using
What command-line interpreters are you using
What OS are you using

## Describe the bug
Fail to install microsoft/bf-orchestrator-cli@beta.
Error message:
```

node-pre-gyp info check checked for "C:\Users\qiowu\AppData\Local\@microsoft\botframework-cli\node_modules\orchestrator-core\orchestrator-core.node" (not found)
node-pre-gyp http GET https://bcmodelsprod.azureedge.net/native/orchestrator-core-v4.10.0-dev.20200831.592468f-node-v79-win32-x64.tar.gz
node-pre-gyp http 404 https://bcmodelsprod.azureedge.net/native/orchestrator-core-v4.10.0-dev.20200831.592468f-node-v79-win32-x64.tar.gz
node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://bcmodelsprod.azureedge.net/native/orchestrator-core-v4.10.0-dev.20200831.592468f-node-v79-win32-x64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (C:\Users\qiowu\AppData\Local\@microsoft\botframework-cli\node_modules\node-pre-gyp\lib\install.js:142:27)
node-pre-gyp ERR! stack     at Request.emit (events.js:327:22)
node-pre-gyp ERR! stack     at Request.onRequestResponse (C:\Users\qiowu\AppData\Local\@microsoft\botframework-cli\node_modules\request\request.js:1059:10)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:315:20)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:610:27)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:116:17)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:479:22)
node-pre-gyp ERR! stack     at TLSSocket.emit (events.js:315:20)
node-pre-gyp ERR! stack     at addChunk (_stream_readable.js:297:12)
node-pre-gyp ERR! stack     at readableAddChunk (_stream_readable.js:273:9)
node-pre-gyp ERR! System Windows_NT 10.0.19041
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\qiowu\\AppData\\Local\\@microsoft\\botframework-cli\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install"
node-pre-gyp ERR! cwd C:\Users\qiowu\AppData\Local\@microsoft\botframework-cli\node_modules\orchestrator-core
node-pre-gyp ERR! node -v v13.12.0
node-pre-gyp ERR! node-pre-gyp -v v0.15.0
node-pre-gyp ERR! not ok
404 status code downloading tarball https://bcmodelsprod.azureedge.net/native/orchestrator-core-v4.10.0-dev.20200831.592468f-node-v79-win32-x64.tar.gz
Unknown error during execution. Please file an issue on https://github.com/microsoft/botframework-cli/issues
yarn add @microsoft/bf-orchestrator-cli@beta --non-interactive --mutex=file:C:\Users\qiowu\AppData\Local\@microsoft\botframework-cli\yarn.lock --preferred-cache-folder=C:\Users\qiowu\AppData\Local\@microsoft\botframework-cli\yarn --check-files exited with code 1
Installing plugin @microsoft/bf-orchestrator-cli... done

```
## To Reproduce
1. Go to cmd
2. npm i -g @microsoft/botframework-cli
3. bf plugins:install @microsoft/bf-orchestrator-cli@beta

**Comment by vishwacsena** [comment]
@tsuwandy can you help take a look?

**Comment by daveta** [comment]
Hi @DingmaomaoBJTU :
We currently build for nodejs 10, 12 & 14 - these are all [long term support releases](https://nodejs.org/en/about/releases/) - would it be possible for you to upgrade to 14 (or downgrade to 12?).
Thanks!

**Comment by DingmaomaoBJTU** [comment]
@daveta Thank you so much! after upgrade to 14, it works~
